### ISSUE TITLE
Build Error: `AttributeError: 'Module' object has no attribute 'doc'`

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#138]
```
Running Sphinx v7.2.5
making output directory... done
[autosummary] generating autosummary for: content/changelog/index.md, content/changelog/link_to_changelog_analyzer.md, content/changelog/link_to_changelog_calc.md, content/changelog/link_to_changelog_data.md, content/changelog/link_to_changelog_io.md, content/faq/brightway.md, content/faq/faq.md, content/installation/installation.md, content/installation/ui.md, content/installation/upgrading.md, index.md
myst v2.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'amsmath', 'colon_fence', 'deflist', 'dollarmath', 'html_image'}, disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/checkouts/legacy/brightway2-io/bw2io/validation.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/checkouts/legacy/brightway2-io/bw2io/tests.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/checkouts/legacy/brightway2-io/bw2io/data/exiopol.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/checkouts/legacy/brightway2-io/bw2io/data/__init__.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/checkouts/legacy/brightway2-data/bw2data/tests.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/checkouts/legacy/brightway2-analyzer/bw2analyzer/version.py
/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/autoapi/mappers/python/mapper.py:293: RemovedInSphinx80Warning: The alias 'sphinx.util.status_iterator' is deprecated, use 'sphinx.util.display.status_iterator' instead. Check CHANGES for Sphinx API modifications.
  for dir_root, path in sphinx.util.status_iterator(
[2K[AutoAPI] Reading files... [  1%] /home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/checkouts/legacy/brightway2-io/bw2io/unlinked_data.py
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/sphinx/events.py", line 97, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/autoapi/extension.py", line 148, in run_autoapi
    if sphinx_mapper_obj.load(
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/autoapi/mappers/python/mapper.py", line 299, in load
    data = self.read_file(path=path, dir_root=dir_root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/autoapi/mappers/python/mapper.py", line 316, in read_file
    parsed_data = Parser().parse_file(path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/autoapi/mappers/python/parser.py", line 41, in parse_file
    return self._parse_file(
           ^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/autoapi/mappers/python/parser.py", line 38, in _parse_file
    return self.parse(node)
           ^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/autoapi/mappers/python/parser.py", line 265, in parse
    data = parse_func(node)
           ^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/autoapi/mappers/python/parser.py", line 240, in parse_module
    "doc": _prepare_docstring(node.doc or ""),
                              ^^^^^^^^
AttributeError: 'Module' object has no attribute 'doc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/sphinx/application.py", line 272, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/sphinx/application.py", line 343, in _init_builder
    self.events.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/brightway-documentation/conda/legacy/lib/python3.11/site-packages/sphinx/events.py", line 108, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function run_autoapi at 0x7fa77f6e07c0> for event 'builder-inited' threw an exception (exception: 'Module' object has no attribute 'doc')

Extension error (autoapi.extension):
Handler <function run_autoapi at 0x7fa77f6e07c0> for event 'builder-inited' threw an exception (exception: 'Module' object has no attribute 'doc')
```

**Comment by michaelweinold** [comment]
...for the `legacy` branch, this was resolved by bumping `sphinx-autoapi` to version 3.
